
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 15 17:47:24 CET 2007
//----------------------------------------------------

package simulator.assembler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ORG = 8;
  public static final int IDENT = 15;
  public static final int RBRACE = 6;
  public static final int INS_INT = 13;
  public static final int REG = 16;
  public static final int COLON = 2;
  public static final int LBRACE = 5;
  public static final int HASH = 7;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DEF = 9;
  public static final int INS_JUMP = 12;
  public static final int LSQUARE = 3;
  public static final int error = 1;
  public static final int RSQUARE = 4;
  public static final int INS_HALT = 14;
  public static final int INVALID = 18;
  public static final int INS_A1 = 11;
  public static final int INS_A0 = 10;
}

